name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Backend build and test
      - name: Backend - install dependencies
        working-directory: ./backend
        run: npm install

      - name: Backend - run tests
        working-directory: ./backend
        run: npm test || echo "No tests found"

      # Frontend build and test
      - name: Frontend - install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Frontend - run tests
        working-directory: ./frontend
        run: npm test || echo "No tests found"

      - name: Build backend Docker image
        run: docker build -t happydevs1/backend:latest ./backend

      - name: Build frontend Docker image
        run: docker build -t happydevs1/frontend:latest ./frontend

      # Login and push to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push backend Docker image
        run: docker push happydevs1/backend:latest

      - name: Push frontend Docker image
        run: docker push happydevs1/frontend:latest
